config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'
  get 'inbox/index'
  get 'inbox/chat/:id', to: 'inbox#get_chat', as: 'getchats'
  get 'inbox/:id', to: 'inbox#chat', as: 'chats'
  post 'inbox/:id', to: 'inbox#create'
  devise_for :users
  resources :impulses
  resources :journals
  # get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/impulse.rb
class Impulse < ApplicationRecord
    belongs_to :user
end

app/models/journal.rb
class Journal < ApplicationRecord
    belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :journals
  has_many :impulses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    # Scope your query to the dates being shown:
    start_date = params.fetch(:start_date, Date.today).to_date
    @meetings = Meeting.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def new
    @meeting = Meeting.new
  end

  def create_event
    # @meeting = Meeting.new()
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
   
  end
end

app/controllers/impulses_controller.rb
class ImpulsesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_impulse, only: %i[ show edit update destroy ]

  # GET /impulses or /impulses.json
  def index
    @impulses = Impulse.all.where(user_id: current_user)
  end

  # GET /impulses/1 or /impulses/1.json
  def show
  end

  # GET /impulses/new
  def new
    @impulse = Impulse.new
  end

  # GET /impulses/1/edit
  def edit
  end

  # POST /impulses or /impulses.json
  def create
    @impulse = current_user.impulses.create(impulse_params)

    respond_to do |format|
      if @impulse.save
        format.html { redirect_to @impulse, notice: "Impulse was successfully created." }
        format.json { render :show, status: :created, location: @impulse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @impulse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /impulses/1 or /impulses/1.json
  def update
    respond_to do |format|
      if @impulse.update(impulse_params)
        format.html { redirect_to @impulse, notice: "Impulse was successfully updated." }
        format.json { render :show, status: :ok, location: @impulse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @impulse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /impulses/1 or /impulses/1.json
  def destroy
    @impulse.destroy
    respond_to do |format|
      format.html { redirect_to impulses_url, notice: "Impulse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_impulse
      @impulse = Impulse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def impulse_params
      params.require(:impulse).permit(:title, :level, :desc, :user_id)
    end
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  before_action :set_user, only: %i[chat]

  def index
    @users = User.all.where.not(id: current_user)
  end

  def chat
    @current_user = current_user
    @other_user_id = params[:id]
    # logger.debug @user.data
    # @chat = Chat.new
    sort_chats()
    
    # end
    # logger.debug hi
    # @chats.each do |cha|
    #   logger.debug cha['id']
    #   # logger.debug cha[:id]
    #   # logger.debug cha.id
    # end
    
  end

  def get_chat
    @current_user = current_user
    
    # logger.debug @user.data
    @chat = Chat.new
    sort_chats()
    # end
    # logger.debug hi
    # @chats.each do |cha|
    #   logger.debug cha['id']
    #   # logger.debug cha[:id]
    #   # logger.debug cha.id
    # end
    render json: {
      sorted_chats: @sorted_chats,
      user: set_user
    }
  end
  

 

  def create
    logger.debug params
    @chat = Chat.create(message: params[:message], sender_id: current_user.id, receiver_id: params[:id])
    logger.debug "This is the current user " + current_user.id.to_s
    
    logger.debug @chat.message 
    logger.debug @chat.sender_id
    logger.debug @chat.receiver_id
    if @chat.save
      sort_chats()
      render json: @sorted_chats  
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def chat_params
      params.require(:chat).permit(:message, :sender_id, :receiver_id)
    end

    def sort_chats
      @my_chats = Chat.all.where(sender_id: current_user.id, receiver_id: params[:id])
      logger.debug @my_chats.as_json.count
      @other_chats = Chat.all.where(sender_id: params[:id], receiver_id: current_user.id)
      logger.debug @other_chats.as_json
      @chats = (@my_chats.as_json)
      @other_chats.as_json.each do |c|
        @chats << c
      end
      @chats = @chats.compact
      # logger.debug @chats
      # unless @chats != []
      @sorted_chats = @chats.sort_by { |c| c["created_at"] }
    end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_journal, only: %i[ show edit update destroy ]

  # GET /journals or /journals.json
  def index
    @journals = Journal.all.where(user_id: current_user)
  end

  # GET /journals/1 or /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals or /journals.json
  def create
    @journal = current_user.journals.create(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to @journal, notice: "Journal was successfully created." }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1 or /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: "Journal was successfully updated." }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1 or /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to journals_url, notice: "Journal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # def get_user_id
    #   if user_signed_in?
    #     self.user_id = current_user
    #   end
    # end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:title, :desc, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/impulses_helper.rb
module ImpulsesHelper
end

app/helpers/inbox_helper.rb
module InboxHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/calendar/index.html.erb
<%= month_calendar(events: @meetings) do |date, meetings| %>
   <a href="#"> <%= date.strftime("%d") %></a>

  <% meetings.each do |meeting| %>
    <div>
      <%= meeting.name %>
    </div>
  <% end %>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
        <%= link_to 'Choices', root_path , class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to 'Journals', journals_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Impulses', impulses_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Calendar', calendar_index_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Inbox', inbox_index_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= button_to 'Sign Out', destroy_user_session_path, method: :delete , data: { confirm: "Really?" } %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
          </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron">
  <header>
    <h1>Welcome to Choices!</h1>
  </header>
  <p>You can record journals, impulses, create events in the calendar and chat with your therapist.</p>
</div>

app/views/impulses/_form.html.erb
<%= form_with(model: impulse) do |form| %>
  <% if impulse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(impulse.errors.count, "error") %> prohibited this impulse from being saved:</h2>

      <ul>
        <% impulse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :level %>
    <%= form.number_field :level, class:"form-control" %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :desc %>
    <%= form.text_area :desc, class:"form-control" %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit btnName, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/impulses/edit.html.erb
<h1>Editing Impulse</h1>

<%= render 'form', impulse: @impulse, btnName: "Update" %>

<%= link_to 'Back', impulses_path, class:"btn btn-secondary back" %>

app/views/impulses/index.html.erb
<h1>Impulses</h1>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @impulses.each do |impulse| %>
      <div class="col">
        <div class="card h-100 position-relative" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= impulse.title %></h5>
            <h5 class="card-text">Level: <%= impulse.level %></h5>
            <% if (impulse.desc.length > 100) %>
              <p class="card-text"><%= impulse.desc[0..100] %>....</p>
            <% else %>
              <p class="card-text"><%= impulse.desc %></p>
            <% end %>
            <%= link_to 'View', impulse, class: "btn btn-primary" %></td>
            <%= link_to 'Edit', edit_impulse_path(impulse), class: "btn btn-secondary" %></td>
            <%= link_to 'Delete', impulse, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<br>

<%= link_to 'New Impulse', new_impulse_path, class:"btn btn-secondary" %>

app/views/impulses/new.html.erb
<h1>New Impulse</h1>

<%= render 'form', impulse: @impulse, btnName: "Add" %>

<%= link_to 'Back', impulses_path, class:"btn btn-secondary back" %>

app/views/impulses/show.html.erb
<br /><br />
<div class="show-journal">
  <h1 class="display-4">
    <%= @impulse.title %>
  </h1>
  <h2 class="lead">
    Level: <%= @impulse.level %>
  </h2>
  <p class="lead desc">
    <%= @impulse.desc %>
  </p>
  <%= link_to 'Edit', edit_impulse_path(@impulse), class:"btn btn-primary btn-lg" %>
  <%= link_to 'Back', impulses_path, class:"btn btn-secondary btn-lg" %>
</div>

app/views/inbox/chat.html.erb
<%= react_component('ChatPage', {other_user: @user, sorted_chats:@sorted_chats, current_user: @current_user}) %>

app/views/inbox/index.html.erb
<% @users.each do |user| %>
    <div>
        <%= link_to user.email, chats_path(user), class: "btn btn-primary" %>
    </div>
<% end %>

app/views/journals/_form.html.erb
<%= form_with(model: journal) do |form| %>
  <% if journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
        <% journal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>
  <br />
  <div class="form-group">
    <%= form.label :desc %>
    <%= form.text_area :desc, class:"form-control" %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit btnName, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Editing Journal</h1>

<%= render 'form', journal: @journal, btnName: "Update" %>


<%= link_to 'Back', journals_path, class:"btn btn-secondary back" %>

app/views/journals/index.html.erb
<h1>Journals</h1>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @journals.each do |journal| %>
        <div class="col">
        <div class="card h-100 position-relative" style="width: 18rem;">
        
          <div class="card-body">
          
            <h5 class="card-title"><%= journal.title %></h5>
            <% if (journal.desc.length > 100) %>
              <p class="card-text"><%= journal.desc[0..100] %>....</p>
            <% else %>
              <p class="card-text"><%= journal.desc %></p>
            <% end %>
            <%= link_to 'View', journal, class: "btn btn-primary" %></td>
            <%= link_to 'Edit', edit_journal_path(journal), class: "btn btn-secondary" %></td>
            <%= link_to 'Delete', journal, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<br>

<%= link_to 'New Journal', new_journal_path, class:"btn btn-secondary" %>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form', journal: @journal, btnName: "Add" %>

<%= link_to 'Back', journals_path, class:"btn btn-secondary back" %>

app/views/journals/show.html.erb
<br /><br />
<div class="show-journal">
  <h1 class="display-4">
    <%= @journal.title %>
  </h1>

  <p class="lead desc">
    <%= @journal.desc %>
  </p>
  <%= link_to 'Edit', edit_journal_path(@journal), class:"btn btn-primary btn-lg" %>
  <%= link_to 'Back', journals_path, class:"btn btn-secondary btn-lg" %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Choices</title>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
      <div class="notice alert alert-primary alert-dismissible fade show" role="alert"><%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    

    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>